import { connectDatabase, disconnectDatabase } from '../config/database';
import { User } from '../models/User';
import { messaging, isFirebaseInitialized } from '../config/firebase';

async function run() {
  console.log('--- FCM Test Script ---');
  try {
    await connectDatabase();
    console.log('Database connected.');

    console.log('Firebase Initialized:', isFirebaseInitialized);
    if (!isFirebaseInitialized || !messaging) {
      console.error('Firebase Admin SDK is not initialized! Please check your credentials.');
      return;
    }

    const users = await User.find({ fcmToken: { $exists: true, $ne: null } }).select('name mobile status fcmToken');
    console.log(`Found ${users.length} users with FCM tokens in DB:`);
    users.forEach((user, idx) => {
      console.log(`[${idx + 1}] Name: ${user.name} | Mobile: ${user.mobile} | Status: ${user.status} | Token: ${user.fcmToken?.substring(0, 20)}...`);
    });

    if (users.length === 0) {
      console.log('No users with registered FCM tokens. To register a token, run the React Native app and log in.');
      return;
    }

    // Try sending a dry run test notification to the first user
    const firstUser = users[0];
    if (!firstUser.fcmToken) {
      console.log('No FCM token found for the first user.');
      return;
    }

    console.log(`Sending dry run push to ${firstUser.name}...`);

    const message = {
      token: firstUser.fcmToken,
      notification: {
        title: 'FCM Verification Notification 🔔',
        body: 'This is a test notification generated by the backend validation script.',
      },
      android: {
        notification: {
          sound: 'default',
          channelId: 'gyaanchakra_alerts',
          priority: 'high' as const,
        },
      },
    };

    // send() has a dryRun option to validate the payload without actually delivering the message
    const response = await messaging.send(message, true); // dryRun = true
    console.log('✅ Firebase Admin SDK successfully validated message payload! Dry run response:', response);
  } catch (error: any) {
    console.error('❌ Error testing FCM:', error.message || error);
  } finally {
    await disconnectDatabase();
    process.exit(0);
  }
}

run();
